//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBankBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuenta()
        {
            this.Movimientos = new HashSet<Movimientos>();
        }
    
        public int cue_id { get; set; }
        public string cue_numero { get; set; }
        public Nullable<int> cli_id { get; set; }
        public Nullable<bool> cue_activa { get; set; }
        public Nullable<System.DateTime> cue_fechacreacion { get; set; }
        public string cue_usuariocreacion { get; set; }
        public Nullable<decimal> cue_saldoactual { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimientos> Movimientos { get; set; }
    }
}
